### ISSUE TITLE
Wrong id return

### ISSUE THREAD

**Issue by rohailparacha** [Appsero/laravel-datastore#1]
When I insert in datastore, the id returned in response is not same as the one generated in datastore. Hence, It becomes difficult to know which record is added. What can be the issue?

**Comment by saiftheboss7** [comment]
@arafatkn Take a look if you get some free time over the week

**Comment by arafatkn** [comment]
@rohailparacha Thanks for raising the issue.

I have investigated the issue. The original datastore SDK (by Google) returns the entity version (the timestamp actually). It's not returning the key. That's why our package is also returning the entity version (timestamp). If the insert fails, then -1 returns.
I will fix the issue soon and update the insert/create and related methods so that these will return the actual key after the insert operation.

**Comment by arafatkn** [comment]
@rohailparacha The issue has been fixed in v0.0.4
Now, insert() will return the inserted data with the keys.
Please update to version v0.0.4
